/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as AcademyCoursesRouteRouteImport } from './routes/academy/courses/route'
import { Route as AcademyStudentWorkRouteImport } from './routes/academy/student-work'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GalleryCategoryRouteImport } from './routes/gallery/$category'
import { Route as OurWorkIndexRouteImport } from './routes/our-work/index'
import { Route as OurWorkSlugRouteImport } from './routes/our-work/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as AcademyCoursesIndexRouteImport } from './routes/academy/courses/index'
import { Route as AcademyCoursesSlugRouteImport } from './routes/academy/courses/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about', 
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCoursesRouteRoute = AcademyCoursesRouteRouteImport.update({
  id: '/academy/courses',
  path: '/academy/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyStudentWorkRoute = AcademyStudentWorkRouteImport.update({
  id: '/academy/student-work',
  path: '/academy/student-work',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCategoryRoute = GalleryCategoryRouteImport.update({
  id: '/gallery/$category',
  path: '/gallery/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkIndexRoute = OurWorkIndexRouteImport.update({
  id: '/our-work/',
  path: '/our-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/our-work/$slug',
  path: '/our-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCoursesIndexRoute = AcademyCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyCoursesRouteRoute,
} as any)
const AcademyCoursesSlugRoute = AcademyCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyCoursesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/academy/courses': typeof AcademyCoursesRouteRouteWithChildren
  '/academy/student-work': typeof AcademyStudentWorkRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/academy/courses/': typeof AcademyCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/academy/student-work': typeof AcademyStudentWorkRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/our-work': typeof OurWorkIndexRoute
  '/services': typeof ServicesIndexRoute
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/academy/courses': typeof AcademyCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/academy/courses': typeof AcademyCoursesRouteRouteWithChildren
  '/academy/student-work': typeof AcademyStudentWorkRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/academy/courses/': typeof AcademyCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/academy/courses'
    | '/academy/student-work'
    | '/gallery/$category'
    | '/our-work/$slug'
    | '/services/$slug'
    | '/academy/'
    | '/gallery/'
    | '/our-work/'
    | '/services/'
    | '/academy/courses/$slug'
    | '/academy/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/academy/student-work'
    | '/gallery/$category'
    | '/our-work/$slug'
    | '/services/$slug'
    | '/academy'
    | '/gallery'
    | '/our-work'
    | '/services'
    | '/academy/courses/$slug'
    | '/academy/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/academy/courses'
    | '/academy/student-work'
    | '/gallery/$category'
    | '/our-work/$slug'
    | '/services/$slug'
    | '/academy/'
    | '/gallery/'
    | '/our-work/'
    | '/services/'
    | '/academy/courses/$slug'
    | '/academy/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  AcademyCoursesRouteRoute: typeof AcademyCoursesRouteRouteWithChildren
  AcademyStudentWorkRoute: typeof AcademyStudentWorkRoute
  GalleryCategoryRoute: typeof GalleryCategoryRoute
  OurWorkSlugRoute: typeof OurWorkSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  OurWorkIndexRoute: typeof OurWorkIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/courses': {
      id: '/academy/courses'
      path: '/academy/courses'
      fullPath: '/academy/courses'
      preLoaderRoute: typeof AcademyCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/student-work': {
      id: '/academy/student-work'
      path: '/academy/student-work'
      fullPath: '/academy/student-work'
      preLoaderRoute: typeof AcademyStudentWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$category': {
      id: '/gallery/$category'
      path: '/gallery/$category'
      fullPath: '/gallery/$category'
      preLoaderRoute: typeof GalleryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/': {
      id: '/our-work/'
      path: '/our-work'
      fullPath: '/our-work/'
      preLoaderRoute: typeof OurWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/our-work/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/courses/': {
      id: '/academy/courses/'
      path: '/'
      fullPath: '/academy/courses/'
      preLoaderRoute: typeof AcademyCoursesIndexRouteImport
      parentRoute: typeof AcademyCoursesRouteRoute
    }
    '/academy/courses/$slug': {
      id: '/academy/courses/$slug'
      path: '/$slug'
      fullPath: '/academy/courses/$slug'
      preLoaderRoute: typeof AcademyCoursesSlugRouteImport
      parentRoute: typeof AcademyCoursesRouteRoute
    }
  }
}

interface AcademyCoursesRouteRouteChildren {
  AcademyCoursesSlugRoute: typeof AcademyCoursesSlugRoute
  AcademyCoursesIndexRoute: typeof AcademyCoursesIndexRoute
}

const AcademyCoursesRouteRouteChildren: AcademyCoursesRouteRouteChildren = {
  AcademyCoursesSlugRoute: AcademyCoursesSlugRoute,
  AcademyCoursesIndexRoute: AcademyCoursesIndexRoute,
}

const AcademyCoursesRouteRouteWithChildren =
  AcademyCoursesRouteRoute._addFileChildren(AcademyCoursesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  AcademyCoursesRouteRoute: AcademyCoursesRouteRouteWithChildren,
  AcademyStudentWorkRoute: AcademyStudentWorkRoute,
  GalleryCategoryRoute: GalleryCategoryRoute,
  OurWorkSlugRoute: OurWorkSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  OurWorkIndexRoute: OurWorkIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
